import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import SmoothScroll from "@/lib/SmoothScroll";



const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = { 
  title: "The nexgenix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-primary`}>
      <SmoothScroll>

        {/* Navbar component */}
        <Navbar/>
        {children}
        {/* footer component */}
        <Footer/>
      </SmoothScroll>
        
        </body>
    </html>
  );
}
